name: Release
on:
  push:
    branches:
      - main
      - beta
      - alpha
      - pre

jobs:
  call-shared-workflow:
    uses: rodbe-io/shared-workflows/.github/workflows/release.yaml@main
    with:
      enable-test-unit: true
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
